// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inputs.proto

package inputs

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Events               []*any.Any `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8341507c7debe4, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetEvents() []*any.Any {
	if m != nil {
		return m.Events
	}
	return nil
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8341507c7debe4, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Request)(nil), "falco.inputs.request")
	proto.RegisterType((*Response)(nil), "falco.inputs.response")
}

func init() { proto.RegisterFile("inputs.proto", fileDescriptor_3f8341507c7debe4) }

var fileDescriptor_3f8341507c7debe4 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x11, 0xb1, 0x95, 0xd8, 0x53, 0x50, 0xd1, 0x9e, 0xa4, 0x27, 0x0f, 0x3a, 0xc1, 0x16,
	0xf4, 0x5c, 0x3f, 0x82, 0x47, 0x6f, 0x6d, 0x98, 0x66, 0xc3, 0x76, 0x33, 0xd9, 0xfc, 0x29, 0xf4,
	0xdb, 0x2f, 0x24, 0x5d, 0x58, 0xf6, 0xfa, 0xe6, 0xf7, 0x9b, 0xf7, 0x58, 0xa5, 0x8d, 0x8d, 0xc1,
	0x83, 0x75, 0x14, 0x88, 0x57, 0xd3, 0x30, 0x4b, 0x82, 0x9c, 0xd5, 0xaf, 0x8a, 0x48, 0xcd, 0x28,
	0xd2, 0x6d, 0x8c, 0x93, 0x18, 0xcc, 0x9a, 0xc1, 0xe6, 0x87, 0x95, 0x0e, 0x8f, 0x11, 0x7d, 0xe0,
	0x1f, 0xac, 0xc0, 0x05, 0x4d, 0xf0, 0x2f, 0x37, 0x6f, 0xb7, 0xef, 0x0f, 0xed, 0x23, 0x64, 0x0d,
	0xce, 0x1a, 0xf4, 0x66, 0xfd, 0xdb, 0x98, 0x86, 0xb1, 0x7b, 0x87, 0xde, 0x92, 0xf1, 0xd8, 0xf6,
	0xac, 0xf4, 0xe8, 0x16, 0x2d, 0x91, 0x7f, 0xb3, 0xbb, 0x54, 0xca, 0x9f, 0xe0, 0x72, 0x02, 0x6c,
	0x25, 0xf5, 0xf3, 0x75, 0x9c, 0x5f, 0xfc, 0x76, 0xff, 0x5f, 0x4a, 0x87, 0x5d, 0x1c, 0x41, 0xd2,
	0x41, 0x24, 0xc6, 0xa3, 0x8c, 0x4e, 0x87, 0x55, 0xc8, 0x59, 0xa3, 0x09, 0x9f, 0x8a, 0x84, 0xdd,
	0x2b, 0x31, 0x58, 0x2d, 0xb2, 0x3d, 0x16, 0x69, 0x59, 0x77, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x54,
	0x2b, 0xed, 0x7e, 0xfc, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Input(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Input(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/falco.inputs.service/input", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Input(context.Context, *Request) (*Response, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Input(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Input not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Input_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Input(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/falco.inputs.service/Input",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Input(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "falco.inputs.service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "input",
			Handler:    _Service_Input_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inputs.proto",
}
