// Code generated by protoc-gen-go. DO NOT EDIT.
// source: outputs.proto

package outputs

import (
	context "context"
	fmt "fmt"
	schema "github.com/falcosecurity/client-go/pkg/api/schema"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The `request` message is the logical representation of the request model.
// It is the input of the `output.service` service.
type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d51c8ffe2768f30, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

// The `response` message is the representation of the output model.
// It contains all the elements that Falco emits in an output along with the
// definitions for priorities and source.
type Response struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Priority             schema.Priority      `protobuf:"varint,2,opt,name=priority,proto3,enum=falco.schema.Priority" json:"priority,omitempty"`
	Source               schema.Source        `protobuf:"varint,3,opt,name=source,proto3,enum=falco.schema.Source" json:"source,omitempty"`
	Rule                 string               `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	Output               string               `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	OutputFields         map[string]string    `protobuf:"bytes,6,rep,name=output_fields,json=outputFields,proto3" json:"output_fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Hostname             string               `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d51c8ffe2768f30, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Response) GetPriority() schema.Priority {
	if m != nil {
		return m.Priority
	}
	return schema.Priority_EMERGENCY
}

func (m *Response) GetSource() schema.Source {
	if m != nil {
		return m.Source
	}
	return schema.Source_SYSCALL
}

func (m *Response) GetRule() string {
	if m != nil {
		return m.Rule
	}
	return ""
}

func (m *Response) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *Response) GetOutputFields() map[string]string {
	if m != nil {
		return m.OutputFields
	}
	return nil
}

func (m *Response) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "falco.outputs.request")
	proto.RegisterType((*Response)(nil), "falco.outputs.response")
	proto.RegisterMapType((map[string]string)(nil), "falco.outputs.response.OutputFieldsEntry")
}

func init() { proto.RegisterFile("outputs.proto", fileDescriptor_2d51c8ffe2768f30) }

var fileDescriptor_2d51c8ffe2768f30 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x8b, 0xdb, 0x30,
	0x10, 0x45, 0x71, 0xe2, 0xc4, 0x4a, 0x52, 0x5a, 0x11, 0x52, 0xe3, 0x4b, 0x4d, 0x4e, 0x2e, 0xb4,
	0x72, 0x70, 0x7b, 0x08, 0xb9, 0x14, 0x0a, 0xed, 0xb1, 0x05, 0xd3, 0x53, 0x2f, 0x8b, 0xed, 0x9d,
	0x38, 0x22, 0xb6, 0xe5, 0xd5, 0x47, 0x20, 0xa7, 0xfd, 0xd5, 0x7b, 0x5f, 0x22, 0xd9, 0x61, 0x43,
	0xd8, 0xc3, 0xde, 0x34, 0x6f, 0xde, 0x7b, 0x1a, 0xbd, 0x11, 0x9e, 0x73, 0xad, 0x5a, 0xad, 0x24,
	0x6d, 0x05, 0x57, 0x9c, 0xcc, 0x77, 0x59, 0x55, 0x70, 0xda, 0x81, 0xc1, 0xa7, 0x92, 0xf3, 0xb2,
	0x82, 0xd8, 0x34, 0x73, 0xbd, 0x8b, 0x15, 0xab, 0x41, 0xaa, 0xac, 0x6e, 0x2d, 0x3f, 0x98, 0xc9,
	0x62, 0x0f, 0x75, 0x66, 0xab, 0x95, 0x87, 0xc7, 0x02, 0x1e, 0x34, 0x48, 0xb5, 0x7a, 0x1a, 0xe0,
	0x89, 0x00, 0xd9, 0xf2, 0x46, 0x02, 0xa1, 0x78, 0x78, 0x16, 0xfa, 0x28, 0x44, 0xd1, 0x34, 0x09,
	0xa8, 0x75, 0xa5, 0xbd, 0x2b, 0xfd, 0xd7, 0xbb, 0xa6, 0x86, 0x47, 0x12, 0x3c, 0x69, 0x05, 0xe3,
	0x82, 0xa9, 0x93, 0x3f, 0x08, 0x51, 0xf4, 0x2e, 0x59, 0x52, 0x3b, 0xd8, 0xe5, 0x3a, 0xdb, 0x4d,
	0x2f, 0x3c, 0xf2, 0x05, 0xbb, 0x92, 0x6b, 0x51, 0x80, 0xef, 0x18, 0xc5, 0xe2, 0x5a, 0x61, 0x7b,
	0x69, 0xc7, 0x21, 0x04, 0x0f, 0x85, 0xae, 0xc0, 0x1f, 0x86, 0x28, 0xf2, 0x52, 0x73, 0x26, 0x4b,
	0xec, 0xda, 0x77, 0xfb, 0x23, 0x83, 0x76, 0x15, 0xf9, 0xd3, 0x87, 0x74, 0xb7, 0x63, 0x50, 0xdd,
	0x4b, 0xdf, 0x0d, 0x9d, 0x68, 0x9a, 0x7c, 0xa6, 0x57, 0x59, 0xd1, 0xfe, 0xb5, 0xf4, 0xaf, 0x01,
	0x7e, 0x1b, 0xee, 0xaf, 0x46, 0x89, 0x53, 0x3a, 0xe3, 0x2f, 0x20, 0x12, 0xe0, 0xc9, 0x9e, 0x4b,
	0xd5, 0x64, 0x35, 0xf8, 0x63, 0x73, 0xd3, 0xa5, 0x0e, 0x7e, 0xe0, 0x0f, 0x37, 0x72, 0xf2, 0x1e,
	0x3b, 0x07, 0x38, 0x99, 0xf4, 0xbc, 0xf4, 0x7c, 0x24, 0x0b, 0x3c, 0x3a, 0x66, 0x95, 0x06, 0x93,
	0x8e, 0x97, 0xda, 0x62, 0x3b, 0xd8, 0xa0, 0xe4, 0x11, 0x8f, 0x25, 0x88, 0x23, 0x2b, 0x80, 0x6c,
	0xb1, 0x23, 0x75, 0x4e, 0x96, 0x37, 0x73, 0x9a, 0x0d, 0x05, 0x1f, 0x5f, 0x99, 0x3f, 0x42, 0x6b,
	0x44, 0x36, 0xd8, 0x29, 0x41, 0xbd, 0x59, 0xbb, 0x46, 0x3f, 0xbf, 0xff, 0x4f, 0x4a, 0xa6, 0xf6,
	0x3a, 0xa7, 0x05, 0xaf, 0x63, 0x43, 0x93, 0x50, 0xe8, 0xf3, 0x8e, 0xe2, 0xa2, 0x62, 0xd0, 0xa8,
	0xaf, 0x25, 0x8f, 0xdb, 0x43, 0x19, 0x67, 0x2d, 0x8b, 0x3b, 0x83, 0xdc, 0x35, 0x7f, 0xe1, 0xdb,
	0x73, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43, 0x06, 0xa0, 0xeb, 0x8f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	// Subscribe to a stream of Falco outputs by sending a stream of requests.
	Sub(ctx context.Context, opts ...grpc.CallOption) (Service_SubClient, error)
	// Get all the Falco outputs present in the system up to this call.
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (Service_GetClient, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Sub(ctx context.Context, opts ...grpc.CallOption) (Service_SubClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[0], "/falco.outputs.service/sub", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceSubClient{stream}
	return x, nil
}

type Service_SubClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type serviceSubClient struct {
	grpc.ClientStream
}

func (x *serviceSubClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceSubClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (Service_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[1], "/falco.outputs.service/get", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_GetClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type serviceGetClient struct {
	grpc.ClientStream
}

func (x *serviceGetClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	// Subscribe to a stream of Falco outputs by sending a stream of requests.
	Sub(Service_SubServer) error
	// Get all the Falco outputs present in the system up to this call.
	Get(*Request, Service_GetServer) error
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Sub(srv Service_SubServer) error {
	return status.Errorf(codes.Unimplemented, "method Sub not implemented")
}
func (*UnimplementedServiceServer) Get(req *Request, srv Service_GetServer) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Sub_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).Sub(&serviceSubServer{stream})
}

type Service_SubServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type serviceSubServer struct {
	grpc.ServerStream
}

func (x *serviceSubServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceSubServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Service_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).Get(m, &serviceGetServer{stream})
}

type Service_GetServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type serviceGetServer struct {
	grpc.ServerStream
}

func (x *serviceGetServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "falco.outputs.service",
	HandlerType: (*ServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "sub",
			Handler:       _Service_Sub_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "get",
			Handler:       _Service_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "outputs.proto",
}
