// Code generated by protoc-gen-go. DO NOT EDIT.
// source: version.proto

package version

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The `request` message is an empty one.
type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d2c07d79758f814, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

// The `response` message contains the version of Falco.
// It provides the whole version as a string and also
// its parts as per semver 2.0 specification (https://semver.org).
type Response struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Major                uint32   `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor                uint32   `protobuf:"varint,3,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch                uint32   `protobuf:"varint,4,opt,name=patch,proto3" json:"patch,omitempty"`
	Prerelease           string   `protobuf:"bytes,5,opt,name=prerelease,proto3" json:"prerelease,omitempty"`
	Build                string   `protobuf:"bytes,6,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d2c07d79758f814, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Response) GetMajor() uint32 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *Response) GetMinor() uint32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *Response) GetPatch() uint32 {
	if m != nil {
		return m.Patch
	}
	return 0
}

func (m *Response) GetPrerelease() string {
	if m != nil {
		return m.Prerelease
	}
	return ""
}

func (m *Response) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "falco.version.request")
	proto.RegisterType((*Response)(nil), "falco.version.response")
}

func init() { proto.RegisterFile("version.proto", fileDescriptor_7d2c07d79758f814) }

var fileDescriptor_7d2c07d79758f814 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x14, 0x45, 0x19, 0xb5, 0x1d, 0x1b, 0x98, 0x4d, 0x10, 0x0d, 0x2e, 0xa4, 0x74, 0xd5, 0x8d, 0x09,
	0x54, 0x57, 0x2e, 0x05, 0x7f, 0xa0, 0x4b, 0x77, 0x99, 0xf8, 0x9c, 0x3e, 0x9d, 0xce, 0x8b, 0x2f,
	0x99, 0x82, 0xff, 0xe2, 0xc7, 0xca, 0x24, 0x51, 0x94, 0x2e, 0xcf, 0xc9, 0xbd, 0x21, 0x37, 0xa2,
	0x39, 0x00, 0x07, 0xa4, 0x41, 0x7b, 0xa6, 0x48, 0xb2, 0x79, 0xb5, 0xbd, 0x23, 0x5d, 0xe4, 0x6a,
	0x21, 0x6a, 0x86, 0x8f, 0x11, 0x42, 0x5c, 0x7d, 0x55, 0xe2, 0x9c, 0x21, 0x78, 0x1a, 0x02, 0x48,
	0x25, 0xea, 0x12, 0x51, 0xd5, 0xb2, 0x5a, 0x2f, 0xb6, 0x3f, 0x28, 0x2f, 0xc4, 0x6c, 0x6f, 0xdf,
	0x88, 0xd5, 0xc9, 0xb2, 0x5a, 0x37, 0xdb, 0x0c, 0xc9, 0xe2, 0x40, 0xac, 0x4e, 0x8b, 0x9d, 0x60,
	0xb2, 0xde, 0x46, 0xb7, 0x53, 0x67, 0xd9, 0x26, 0x90, 0x37, 0x42, 0x78, 0x06, 0x86, 0x1e, 0x6c,
	0x00, 0x35, 0x4b, 0xd7, 0xff, 0x31, 0x53, 0xab, 0x1d, 0xb1, 0x7f, 0x51, 0xf3, 0x74, 0x94, 0x61,
	0xf3, 0x24, 0xea, 0x00, 0x7c, 0x40, 0x07, 0xf2, 0xe1, 0xf7, 0x71, 0xf2, 0x52, 0xff, 0xdb, 0xa3,
	0xcb, 0x98, 0xeb, 0xab, 0x23, 0x9f, 0x87, 0x3d, 0xde, 0x3f, 0x6f, 0x3a, 0x8c, 0xbb, 0xb1, 0xd5,
	0x8e, 0xf6, 0x26, 0x85, 0x02, 0xb8, 0x91, 0x31, 0x7e, 0x1a, 0xd7, 0x23, 0x0c, 0xf1, 0xb6, 0x23,
	0xe3, 0xdf, 0x3b, 0x63, 0x3d, 0x9a, 0x52, 0x6f, 0xe7, 0xe9, 0xf3, 0xee, 0xbe, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xd0, 0x42, 0x18, 0x3e, 0x4d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Version(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Version(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/falco.version.service/version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Version(context.Context, *Request) (*Response, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Version(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/falco.version.service/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Version(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "falco.version.service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "version",
			Handler:    _Service_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "version.proto",
}
